# Generated by Django 2.1.3 on 2018-11-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_annotatedrecording_recitation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TajweedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=32)),
                ('recording_id', models.CharField(max_length=32)),
                ('platform', models.CharField(default='web', max_length=32)),
                ('letter', models.CharField(max_length=1)),
                ('letter_position', models.IntegerField(default=0)),
                ('degree', models.CharField(choices=[('jali', 'Jali'), ('khafi', 'Khafi')], default='jali', max_length=32)),
                ('category', models.CharField(choices=[('madd', 'Prolongation'), ('tafkheem', 'Fattening'), ('tarqeeq', 'Thinning'), ('makharij', 'Emission'), ('noon', 'Noon'), ('meem', 'Meem'), ('qalqala', 'Echo'), ('other', 'Other')], default='madd', max_length=32)),
            ],
        ),
    ]
