# Generated by Django 2.1.3 on 2018-11-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_tajweedinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TajweedInformation',
        ),
    ]
