# Generated by Django 2.1.3 on 2018-12-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_delete_tajweedinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedrecording',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
