# Generated by Django 2.1.3 on 2018-12-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_annotatedrecording_is_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedrecording',
            name='associated_demographic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.DemographicInformation'),
        ),
    ]
