# Generated by Django 2.1.3 on 2018-12-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_annotatedrecording_associated_demographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedrecording',
            name='associated_demographic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.DemographicInformation'),
        ),
    ]
