# Generated by Django 2.1.3 on 2018-12-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_auto_20181227_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographicinformation',
            name='country',
        ),
    ]
