""" Manually generated by Anas Abou Allaban(piraka9011).
    Taken from: https://bit.ly/2SnPJO1
"""
from __future__ import unicode_literals

from django.db import migrations


def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    site_model = apps.get_model('sites', 'Site')
    site_model.objects.all().delete()

    # Register SITE_ID = 1
    site_model.objects.create(pk=1, domain='tarteel.io', name='tarteel')
    # Register SITE_ID = 2
    site_model.objects.create(pk=2, domain='127.0.0.1', name='tarteel-test')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites)
    ]

